source 'https://rubygems.org'

gem 'sinatra'
gem 'unicorn'
gem 'redis', '~> 3.0.4'
gem 'activesupport'
gem 'faraday', '~> 0.9.0'
gem "koala", "~> 2.2"
gem 'json'
gem 'sequel'
gem 'sidekiq', '~> 2.15.2'
gem 'sidekiq-middleware'
gem 'sidekiq-failures'
gem 'mime-types', '~> 1.25'
gem 'typhoeus', '~> 0.6'
gem 'gatekeeperizer', :git => 'git@github.com:vitrue/gatekeeperizer.git', :tag => 'v1.0.5'
gem 'brokerizer', :git => 'git@github.com:vitrue/brokerizer.git', :tag => 'v6.5.2.2'
gem 'healthcheck-middleware', git: 'git@github.com:vitrue/healthcheck-middleware.git'
gem 'bunny', '~> 1.7.1'
gem 'rake'
gem 'pry'
gem 'amqp', '~> 1.5.1'
gem 'event-subscriber', :git => 'git@github.com:vitrue/event-subscriber.git', :tag => 'v1.1.2'
gem 'newrelic_rpm'
gem 'pg'
