defaults: &defaults
  amqp_url: <%= ENV['AMQP_URL'] %>
  nb_of_workers: 1
  prefetch_nb: 1

publish_defaults: &publish_defaults
  <<: *defaults
  exchange_name: <%= ENV['FB_PUBLISHING_EXCHANGE_NAME'] %>
  queue_name: <%= ENV['FB_PUBLISHING_QUEUE_NAME'] %>
  threshold: 10


development:
  publisher:
    <<: *publish_defaults
    exchange_name: <%= ENV['FB_PUBLISHING_EXCHANGE_NAME'] || 'publisher.publish.fb-development' %>
    queue_name: <%= ENV['FB_PUBLISHING_QUEUE_NAME'] || 'publisher.publish.fb.queue-development' %>

sandbox:
  publisher:
    <<: *publish_defaults
    exchange_name: 'publisher.publish.tumblr-sandbox'
    queue_name: 'publisher.publish.tumblr.queue-sandbox'
    host: 'int-rabbitmq.rabbitmq-staging.cloud.vitrue.com'
    port: 5672
    pass: 'ThisIsNotProd'
    user: 'vitrue'

integration:
  publisher:
    <<: *publish_defaults

staging:
  publisher:
    <<: *publish_defaults

production:
  publisher:
    <<: *publish_defaults

