defaults: &defaults
  publisher_response:
    queue_name: 'publisher.response.queue'
    threshold: 10

development:
  <<: *defaults

sandbox:
  <<: *defaults
  publisher_response:
    queue_name: 'publisher.response.queue-sandbox'

integration:
  <<: *defaults
  publisher_response:
    queue_name: 'publisher.response.queue-integration'

staging:
  <<: *defaults
  publisher_response:
    queue_name: 'publisher.response.queue-staging'
    threshold: 10
  trey:
    queue_name: 'broker_to_trey_queue'
    threshold: 50

production:
  <<: *defaults
  trey:
    queue_name: 'broker.calls'
    threshold: 200

