efault: &default
  namespace: tumblr

test:
  <<: *default

development:
  <<: *default
  host: localhost
  port: 6379
  db: 15

sandbox:
  <<: *default
  host: localhost
  port: 6379
  db: 15

integration:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
