default: &default
  publisher:
    pidfile: 'tmp/pids/sidekiq_publisher.pid'
    logfile: 'log/sidekiq_publisher.log'
    errlog: 'log/sidekiq_publisher.err'
  accounts:
    pidfile: 'tmp/pids/sidekiq_accounts.pid'
    logfile: 'log/sidekiq_accounts.log'
    errlog: 'log/sidekiq_accounts.err'
  analytics:
    pidfile: 'tmp/pids/sidekiq_analytics.pid'
    logfile: 'log/sidekiq_analytics.log'
    errlog: 'log/sidekiq_analytics.err'
  stats:
    pidfile: 'tmp/pids/sidekiq_stats.pid'
    logfile: 'log/sidekiq_stats.log'
    errlog: 'log/sidekiq_stats.err'
  monitoring:
    username: 'admin'
    password: 'apocalypse'

test:
  <<: *default

development:
  <<: *default

sandbox:
  <<: *default

integration:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
